### ISSUE TITLE
coordinates being received as object.

### ISSUE THREAD

**Issue by Cryptonex7** [Covid-Analytics-India/covid19-analysis#3]
Coordinates are beinf recieved as objects,

A list is needed instead.

- Current response: 
  -- `ypoints: {
         1: 1,
         2: 5, ...
      }`
- Expected response: 
  -- `ypoints: [ 1, 5, 6, 19, ...]`

**Comment by atharvu1** [comment]
Resolved, see 'updates' branch and merge it.
