### ISSUE TITLE
Provide a list of state codes in order of the states.

### ISSUE THREAD

**Issue by Cryptonex7** [Covid-Analytics-India/covid19-analysis#32]
- The State names for the Heat Map is needed to be converted into  State Codes.
    - The State Names Key has to be preserved for the bar graph.

`switch (state) {
      case 'West Bengal':
        return 'WB';
      case 'Odisha':
        return 'OD';
      case 'Andhra Pradesh':
        return 'AP';
      case 'Jammu and Kashmir':
        return 'JK';
      case 'Ladakh':
        return 'LD';
      case 'Uttarakhand':
        return 'UK';
      case 'Uttar Pradesh':
        return 'UP';
      case 'Tripura':
        return 'TR';
      case 'Telangana':
        return 'TG';
      case 'Tamil Nadu':
        return 'TN';
      case 'Sikkim':
        return 'SK';
      case 'Rajasthan':
        return 'RJ';
      case 'Punjab':
        return 'PB';
      case 'Puducherry':
        return 'PD';
      case 'Delhi':
        return 'DL';
      case 'Nagaland':
        return 'NL';
      case 'Mizoram':
        return 'MZ';
      case 'Meghalaya':
        return 'MG';
      case 'Manipur':
        return 'MN';
      case 'Maharashtra':
        return 'MH';
      case 'Madhya Pradesh':
        return 'MP';
      case 'Lakshadweep':
        return 'LD';
      case 'Kerala':
        return 'KL';
      case 'Karnataka':
        return 'KR';
      case 'Jharkhand':
        return 'JK';
      case 'Himachal Pradesh':
        return 'HP';
      case 'Haryana':
        return 'HR';
      case 'Gujarat':
        return 'GJ';
      case 'Goa':
        return 'GA';
      case 'Daman and Diu':
        return 'DD';
      case 'Dadra and Nagar Haveli':
        return 'DN';
      case 'Chhattisgarh':
        return 'CT';
      case 'Chandigarh':
        return 'CH';
      case 'Bihar':
        return 'BR';
      case 'Assam':
        return 'AS';
      case 'Arunachal Pradesh':
        return 'AR';
      case 'Andaman and Nicobar Islands':
        return 'AN';
      default:
        return '';
    }`

**Comment by atharvu1** [comment]
provided
