### ISSUE TITLE
Unexpected JSON response for Bar Graphs and Pie Charts

### ISSUE THREAD

**Issue by Cryptonex7** [Covid-Analytics-India/covid19-analysis#33]
- A list with a single object doesnt make sense
- the object is the trace of the graph and that is what is required
- convert `<foo>: [ {...} ]` to `<foo>: {...}`

![image](https://user-images.githubusercontent.com/34197902/79690337-958d3580-8277-11ea-9db3-8dc238d24a2e.png)

**Comment by atharvu1** [comment]
solved
